baseURL = 'https://dailyjavablogs.github.io/'
languageCode = 'en-us'
pagination.pagerSize = 10
title = 'Daily Java Blogs'
theme = "PaperMod"
googleAnalytics = 'G-EMVT5TFRDE'

[module]
[[module.imports]]
    disable = false
    path = 'github.com/hugomods/google-adsense'

[params]
    environment = "production"
    keywords = ["Java", "Blog"]
    disableThemeToggle = false
    defaultTheme= "auto" # dark, light

    ShowReadingTime = false
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = false
    ShowWordCount = false
    ShowRssButtonInSectionTermList = false
    ShowPageNums = true
    UseHugoToc = false
    disableSpecial1stPost = true
    disableScrollToTop = true
    comments = false
    hidemeta = false
    hideSummary = false
    showtoc = false
    tocopen = false
    google_adsense = 'ca-pub-5778986975506542'

    [params.cover]
        hidden = true
        hiddenInList = true
        hiddenInSingle = true